apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tenant-api
  labels:
    app: tenant-api
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-natron
spec:
  rules:
  - host: api.example.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: tenant-api
            port:
              number: 8000
  tls:
  - hosts:
    - api.example.com
    secretName: api-natron-io-cert
